-- 학생
CREATE TABLE "TABLE" (
	"ID" INTEGER NOT NULL -- ID,
	"NAME" VARCHAR(255) NULL -- 이름,
	"ADDRESS" VARCHAR(255) NULL -- 주소,
	"TELEPHONE" VARCHAR(255) NULL -- 전화번호,
	"EMAIL" VARCHAR(255) NULL -- 이메일,
	"AGE" INTEGER NULL -- 나이,
	"GENDER" VARCHAR(255) NULL -- 성별
);

-- 학생
ALTER TABLE "TABLE"
	ADD CONSTRAINT "PK_TABLE" -- 학생 기본키
	PRIMARY KEY (
		"ID" -- ID
	);

-- 수강
CREATE TABLE "TABLE2" (
	"ID" INTEGER NOT NULL -- ID,
	"SUBJECT" VARCHAR(255) NULL -- 과목명,
	"STUDENT_ID" INTEGER NULL -- 학생_ID,
	"LECTURER_ID" INTEGER NULL -- 교수_ID
);

-- 수강
ALTER TABLE "TABLE2"
	ADD CONSTRAINT "PK_TABLE2" -- 수강 기본키
	PRIMARY KEY (
		"ID" -- ID
	);

-- 교수
CREATE TABLE "TABLE3" (
	"ID" INTEGER NOT NULL -- ID,
	"NAME" VARCHAR(255) NULL -- 이름,
	"ADDRESS" VARCHAR(255) NULL -- 주소,
	"TELEPHONE" VARCHAR(255) NULL -- 전화번호,
	"EMAIL" VARCHAR(255) NULL -- 이메일,
	"AGE" INTEGER NULL -- 나이,
	"GENDER" VARCHAR(255) NULL -- 성별
);

-- 교수
ALTER TABLE "TABLE3"
	ADD CONSTRAINT "PK_TABLE3" -- 교수 기본키
	PRIMARY KEY (
		"ID" -- ID
	);

-- 수강
ALTER TABLE "TABLE2"
	ADD CONSTRAINT "FK_TABLE_TO_TABLE2" -- 학생 -> 수강
	FOREIGN KEY (
		"STUDENT_ID" -- 학생_ID
	)
	REFERENCES "TABLE" ( -- 학생
		"ID" -- ID
	);

-- 수강
ALTER TABLE "TABLE2"
	ADD CONSTRAINT "FK_TABLE3_TO_TABLE2" -- 교수 -> 수강
	FOREIGN KEY (
		"LECTURER_ID" -- 교수_ID
	)
	REFERENCES "TABLE3" ( -- 교수
		"ID" -- ID
	);
